// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDN1qjbQAfsPALWpIbmY21eeR70coNdo',
    appId: '1:774520268567:web:7b3f3c75224afc724d3952',
    messagingSenderId: '774520268567',
    projectId: 'arac-sarsinti',
    authDomain: 'arac-sarsinti.firebaseapp.com',
    storageBucket: 'arac-sarsinti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA8Esvw0NK2y_Npl_9_73B8xNejBXAQ3w',
    appId: '1:774520268567:android:697100be4023ce364d3952',
    messagingSenderId: '774520268567',
    projectId: 'arac-sarsinti',
    storageBucket: 'arac-sarsinti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacd6LxUBM2AurjmYTU-Xb9fCduYEU0kA',
    appId: '1:774520268567:ios:d78fd13574121a814d3952',
    messagingSenderId: '774520268567',
    projectId: 'arac-sarsinti',
    storageBucket: 'arac-sarsinti.appspot.com',
    iosBundleId: 'com.example.aracSarsinti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDacd6LxUBM2AurjmYTU-Xb9fCduYEU0kA',
    appId: '1:774520268567:ios:9687ee82770cd7504d3952',
    messagingSenderId: '774520268567',
    projectId: 'arac-sarsinti',
    storageBucket: 'arac-sarsinti.appspot.com',
    iosBundleId: 'com.example.aracSarsinti.RunnerTests',
  );
}
